Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(1, 'John', 'Smith', 'Cardiologist', '123-456-7890', 'dr.smith@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(2, 'Emma', 'Johnson', 'Dermatologist', '234-567-8901', 'dr.johnson@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(3, 'Michael', 'Davis', 'Pediatrician', '345-678-9012', 'dr.davis@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(4, 'Jessica', 'Anderson', 'Orthopedic Surgeon', '456-789-0123', 'dr.anderson@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(5, 'William', 'Brown', 'Neurologist', '567-890-1234', 'dr.brown@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(6, 'Sophia', 'Miller', 'Ophthalmologist', '678-901-2345', 'dr.miller@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(7, 'Daniel', 'Wilson', 'Psychiatrist', '789-012-3456', 'dr.wilson@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(8, 'Olivia', 'Moore', 'ENT Specialist', '890-123-4567', 'dr.moore@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(9, 'Liam', 'Taylor', 'Gastroenterologist', '901-234-5678', 'dr.taylor@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(10, 'Ava', 'Martinez', 'Rheumatologist', '012-345-6789', 'dr.martinez@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(11, 'Ethan', 'Harris', 'Cardiologist', '123-456-7890', 'dr.harris@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(12, 'Avery', 'Jackson', 'Dermatologist', '234-567-8901', 'dr.jackson@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(13, 'Sophie', 'White', 'Pediatrician', '345-678-9012', 'dr.white@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(14, 'Henry', 'Martinez', 'Orthopedic Surgeon', '456-789-0123', 'dr.martinez@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(15, 'Amelia', 'Turner', 'Neurologist', '567-890-1234', 'dr.turner@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(16, 'Jackson', 'Fisher', 'Ophthalmologist', '678-901-2345', 'dr.fisher@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(17, 'Lily', 'Baker', 'Psychiatrist', '789-012-3456', 'dr.baker@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(18, 'Scarlett', 'Thompson', 'Gastroenterologist', '901-234-5678', 'dr.thompson@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(19, 'Logan', 'Hill', 'Rheumatologist', '012-345-6789', 'dr.hill@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(20, 'Ethan', 'Harris', 'Cardiologist', '123-456-7890', 'dr.harris@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(21, 'Avery', 'Jackson', 'Dermatologist', '234-567-8901', 'dr.jackson@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(22, 'Sophie', 'White', 'Pediatrician', '345-678-9012', 'dr.white@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(23, 'Henry', 'Martinez', 'Orthopedic Surgeon', '456-789-0123', 'dr.martinez@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(24, 'Amelia', 'Turner', 'Neurologist', '567-890-1234', 'dr.turner@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(25, 'Jackson', 'Fisher', 'Ophthalmologist', '678-901-2345', 'dr.fisher@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(26, 'Lily', 'Baker', 'Psychiatrist', '789-012-3456', 'dr.baker@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(27, 'Carter', 'Ward', 'ENT Specialist', '890-123-4567', 'dr.ward@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(28, 'Scarlett', 'Thompson', 'Gastroenterologist', '901-234-5678', 'dr.thompson@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(29, 'Logan', 'Hill', 'Rheumatologist', '012-345-6789', 'dr.hill@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(30, 'Michael', 'Johnson', 'Dermatologist', '555-123-4567', 'michael.johnson@example.com');
