Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(1, 'John', 'Smith', 'Cardiologist', '123-456-7890', 'dr.smith@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(2, 'Emma', 'Johnson', 'Dermatologist', '234-567-8901', 'dr.johnson@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(3, 'Michael', 'Davis', 'Pediatrician', '345-678-9012', 'dr.davis@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(4, 'Jessica', 'Anderson', 'Orthopedic Surgeon', '456-789-0123', 'dr.anderson@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(5, 'William', 'Brown', 'Neurologist', '567-890-1234', 'dr.brown@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(6, 'Sophia', 'Miller', 'Ophthalmologist', '678-901-2345', 'dr.miller@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(7, 'Daniel', 'Wilson', 'Psychiatrist', '789-012-3456', 'dr.wilson@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(8, 'Olivia', 'Moore', 'ENT Specialist', '890-123-4567', 'dr.moore@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(9, 'Liam', 'Taylor', 'Gastroenterologist', '901-234-5678', 'dr.taylor@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(10, 'Ava', 'Martinez', 'Rheumatologist', '012-345-6789', 'dr.martinez@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(11, 'Ethan', 'Harris', 'Cardiologist', '123-456-7890', 'dr.harris@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(12, 'Avery', 'Jackson', 'Dermatologist', '234-567-8901', 'dr.jackson@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(13, 'Sophie', 'White', 'Pediatrician', '345-678-9012', 'dr.white@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(14, 'Henry', 'Martinez', 'Orthopedic Surgeon', '456-789-0123', 'dr.martinez@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(15, 'Amelia', 'Turner', 'Neurologist', '567-890-1234', 'dr.turner@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(16, 'Jackson', 'Fisher', 'Ophthalmologist', '678-901-2345', 'dr.fisher@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(17, 'Lily', 'Baker', 'Psychiatrist', '789-012-3456', 'dr.baker@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(18, 'Scarlett', 'Thompson', 'Gastroenterologist', '901-234-5678', 'dr.thompson@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(19, 'Logan', 'Hill', 'Rheumatologist', '012-345-6789', 'dr.hill@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(20, 'Ethan', 'Harris', 'Cardiologist', '123-456-7890', 'dr.harris@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(21, 'Avery', 'Jackson', 'Dermatologist', '234-567-8901', 'dr.jackson@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(22, 'Sophie', 'White', 'Pediatrician', '345-678-9012', 'dr.white@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(23, 'Henry', 'Martinez', 'Orthopedic Surgeon', '456-789-0123', 'dr.martinez@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(24, 'Amelia', 'Turner', 'Neurologist', '567-890-1234', 'dr.turner@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(25, 'Jackson', 'Fisher', 'Ophthalmologist', '678-901-2345', 'dr.fisher@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(26, 'Lily', 'Baker', 'Psychiatrist', '789-012-3456', 'dr.baker@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(27, 'Carter', 'Ward', 'ENT Specialist', '890-123-4567', 'dr.ward@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(28, 'Scarlett', 'Thompson', 'Gastroenterologist', '901-234-5678', 'dr.thompson@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(29, 'Logan', 'Hill', 'Rheumatologist', '012-345-6789', 'dr.hill@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(30, 'Michael', 'Johnson', 'Dermatologist', '555-123-4567', 'michael.johnson@example.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(31, 'Adam', 'Marie', 'Cardiologist', '098-105-6674', 'dr.adammarie@yahoo.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(32, 'Agan', 'June', 'Neurologist',	'345-105-2231',	'dr.aganjune@yahoo.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(33,	'Adams', 'Kara', 'Dermatologist','908-002-1043', 'dr.karaadams@yahoo.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(34, 'Aguilar', 'Casey','Gastroenterologist', '506-889-4460', 'dr.aguilar@yahoo.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(35,	'Akins','Erin',	'Pediatrician',	'607-201-0004',	'dr.erin@yahoo.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(36,	'Acevedo', 'Zoe', 'Gastroenterologist', '103-405-0098',	'dr.acevedo@gmail.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(37, 'Alexander', 'James', 'Rheumatologist',	'506-305-7568',	'dr.alexanderjames@gmail.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(38,	'Allen', 'Daniel', 'Cardiologist',	'295-837-2954',	'dr.allendaniel@gmail.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(39,	'Alonso', 'Isaiah',	'Dermatologist', '687-023-4768', 'dr.isaiah@gmail.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(40,	'Alvarez', 'Harold','Rheumatologist','485-864-1960','dr.alvarez@gmail.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(41,	'Amanti', 'Jessica', 'Ophthalmologist',	'306-890-4578',	'dr.amanti@yahoo.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(42,	'Amerson', 'Josh', 'Pediatrician', '204-465-9586',	'dr.amersonjosh@yahoo.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(43,	'Anderson', 'Andrew', 'Ophthalmologist', '507-375-6078', 'dr.andrew@yahoo.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(44,	'Antoine','Naisya',	'Rheumatologist', '275-097-1948', 'dr.naisya@gmail.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(45,	'Arango', 'Annmarie', 'Rheumatologist',	'098-158-0965',	'dr.arangoannmarie@gmail.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(46, 'Arevalo', 'Ryan', 'Dermatologist','176-960-1654',	'dr.ryan@gmail.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(47,	'Arias','Rose', 'Rheumatologist','205-697-5687', 'dr.ariasrose@gmail.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(48,	'Armstrong', 'Layne', 'Cardiologist', '206-350-6978', 'dr.layne@gmail.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(49,	'Arney', 'Kira', 'Rheumatologist', '205-275-6790', 'dr.kira@gmail.com');
Insert into Doctors(DoctorID, FirstName, LastName, Specialization, ContactNumber, Email) values(50,	'Arnold', 'Conner',	'Dermatologist','406-679-2454',	'dr.arnoldconner@gmail.com');